### ISSUE TITLE
branches

### ISSUE THREAD

**Issue by XenGi** [tr-lonelyrobot/reedb#12]
This repo needs more branches.
master, develop, and some release and feature branches.
Use git-flow, it's awesome.

**Comment by SpaceKookie** [comment]
I'll use git flow as soon as there is a stable and a develop version.
Until then multiple branches just make things more complicated :P

**Comment by XenGi** [comment]
Sure. ;)
Btw: http://danielkummer.github.io/git-flow-cheatsheet/
