### ISSUE TITLE
Backup content of ReeDB

### ISSUE THREAD

**Issue by XenGi** [tr-lonelyrobot/reedb#17]
Is there a way to backup all vaults and reimport them if needed? An encrypted backup file could be saved on a regular basis and auto uploaded to some place i.e. ftp, ssh or smb.
The auto upload sounds more like a bonus feature for a future version but the generation of a backup file is a pretty important feature. In case of a faulty hard drive al vault data would be lost if not backuped.

**Comment by SpaceKookie** [comment]
Originally backing up vault data seemed out of scope. The idea was that vaults could be placed somewhere on the system and synced with whatever service the user wanted to use.

Looking at it in the context of a password manager, some users might throw their vault file into a Dropbox share. Insecure and terrible, yes. Convenient for them, yes.
Others might want to use something like Spideroak or Wuala while others have their own stuff setup.

It is an interesting idea to think about, letting the daemon manage some other sync methods itself. But originally it wasn't planned. Then again, Reedb (still not sure what the spelling should be ;) ) was planned to be the backend for a password manager, nothing else.

I'll think about it.

**Comment by XenGi** [comment]
Totally forgot that it's file based. Then I can just throw my vaults in my syncthing folder and be happy. :)
